- name: resolv.conf içeriğini görüntüle
  hosts: all
  gather_facts: no

  tasks:
    - name: resolv.conf içeriğini oku
      ansible.builtin.command: cat /etc/resolv.conf
      register: resolv_out
      become: yes

    - name: stdout'u fact olarak kaydet
      set_fact:
        resolv_text: "{{ resolv_out.stdout }}"

    - name: resolv.conf içeriğini göster
      ansible.builtin.debug:
        msg: "{{ resolv_text.split('\n') }}"
