- name: 8.8.8.8 DNS kontrolü
  hosts: all
  gather_facts: no

  tasks:
    - name: resolv.conf dosyasını oku
      ansible.builtin.command: cat /etc/resolv.conf
      register: resolv_out
      become: yes
      changed_when: false

    - name: nameserver satırlarını ayıkla
      set_fact:
        nameservers: "{{ resolv_out.stdout_lines | select('search', '^nameserver') | list }}"

    - name: 8.8.8.8 VAR mı?
      ansible.builtin.debug:
        msg: "✅ {{ inventory_hostname }} → 8.8.8.8 VAR"
      when: "'nameserver 8.8.8.8' in nameservers"

    - name: 8.8.8.8 YOK mu?
      ansible.builtin.debug:
        msg: "❌ {{ inventory_hostname }} → 8.8.8.8 YOK"
      when: "'nameserver 8.8.8.8' not in nameservers"
