- name: resolv.conf kontrol ve nameserver ekleme
  hosts: all
  gather_facts: no

  tasks:
    - name: resolv.conf içeriğini oku
      ansible.builtin.command: cat /etc/resolv.conf
      register: resolv_out
      become: yes

    - name: stdout'u fact olarak kaydet
      set_fact:
        resolv_text: "{{ resolv_out.stdout }}"

    - name: nameserver 8.8.8.8 yoksa ekle
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 8.8.8.8"
        state: present
      become: yes
      when: "'nameserver 8.8.8.8' not in resolv_text"

    - name: resolv.conf içeriğini göster
      ansible.builtin.debug:
        msg: "{{ resolv_text.split('\n') }}"
